version: "3.4"
services:
  dumper:
    build: .
    volume:
      - ./backup:/mnt
    environment:
      # for backup all databases set this env by true, else it will backup only one database.
      - BACKUP_ALL=true
      - VOLUME_DIR=/mnt
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_SERVICE_NAME=postgresql
      - POSTGRESQL_SERVICE_PORT=5432
      - POSTGRESQL_USERNAME=user1
      - POSTGRESQL_DB_NAME=db1
      - POSTGRESQL_BACKUP_DIR=post
      - POSTGRESQL_CRON_PATTERN=* 2 * * *
      - BACKUP_TIME=7
      # Choose either s3 or ssh and then configure the required envs
      - REMOTE_BACKUP=s3
      # AWS s3 env variables
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - BUCKET_NAME=
      # SSH env variables
      - REMOTE_HOST=10.107.148.24
      - REMOTE_DIR=/home/ddd
      - REMOTE_SERVER_PORT=22
      - REMOTE_USER=user 
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
