version: "3.4"
services:
  dumper:
    image: $CUSTOM_IMAGE
    volumes: 
      - "./persist:/mnt"
    environment:
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_SERVICE_NAME=postgresql
      - POSTGRESQL_SERVICE_PORT=5432
      - POSTGRESQL_USERNAME=user1
      - POSTGRESQL_DB_NAME=db1
      - POSTGRESQL_BACKUP_DIR=post
      - POSTGRESQL_CRON_PATTERN=* 2 * * *
      - BACKUP_TIME=7
      - REMOTE_BACKUP=true
      - REMOTE_HOST=10.107.148.24
      - REMOTE_DIR=/home/ddd
      - REMOTE_SERVER_PORT=22
      - REMOTE_USER=user
      
