apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-nfs-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /nfs-share/backup
    server: 192.168.1.5
  persistentVolumeReclaimPolicy: Delete
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
